#!/bin/bash

export SLACKROOTDIR="$1"
ARCH="x86_64"
VERSION="current"
MIRRORSCRIPT=/root/mirror-slackware-current.sh
A=""
[ "$ARCH" = "x86_64" ] && A="64"
declare -a failures

mirror() {
  "$MIRRORSCRIPT" -a "$ARCH" -r "$VERSION" -f
  verify
}

verify_dir() {
	for pkg in "$1/*.t?z"
	do
		echo -n "Checking $pkg ... "
		if gpg --verify ${pkg}.asc $pkg &>/dev/null
		then
			echo -e "\033[32mOK\033[0m"
		else
			echo -e "\033[31mNOT OK\033[0m"
			failures[${#failures[*]}]=$pkg
		fi
	done
}

verify() {
	for dir in a ap d e f k kde kdei l n t tcl x xap xfce y
	do
		verify_dir "${SLACKROOTDIR}/slackware${A}-${VERSION}/slackware${A}/$dir"
	done
	check_failures
}

check_failures() {
	if [ ${#failures[*]} -gt 0 ]
	then
		echo; echo "----------------";
		echo "Failures:"
		for fail in ${failures[@]}
		do
			echo $fail
			rm "$fail" "$fail.asc"
		done
		unset failures
		declare -a failures
		mirror
	fi
}

mirror
